-- See database/migrations/sqlite/001_unique_cheque_no.sql for why this
-- exists. The app's MySQL collation (utf8mb4_unicode_ci from
-- database/schema.mysql.sql) is case-insensitive, so this plain UNIQUE index
-- rejects cheque numbers that differ only by case, consistent with the
-- application's portable LOWER(column) = LOWER(?) lookups.
--
-- Before applying to a database that already has cheque data, confirm there
-- are no existing duplicates:
--   SELECT cheque_no, COUNT(*) FROM cheques GROUP BY cheque_no HAVING COUNT(*) > 1;
-- This migration will fail loudly if any are found — resolve them first.
ALTER TABLE cheques ADD UNIQUE INDEX idx_cheques_cheque_no_unique (cheque_no);
