-- Baseline schema for an empty MySQL/MariaDB database. This is what
-- config/database.php applies when DB_DRIVER=mysql and the target database
-- (created by you, never by this app) has no tables yet. It is a dialect
-- translation of database/schema.sqlite.sql — same tables, same columns,
-- same seed data — see database/MIGRATION_MYSQL.md for the exact type
-- mapping used and why.
--
-- Do not edit this file to change structure once it has shipped — add a new
-- numbered file under database/migrations/mysql/ instead. This file only
-- describes what an empty database gets right now.

SET NAMES utf8mb4;

CREATE TABLE schema_migrations (
    migration VARCHAR(255) PRIMARY KEY,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE roles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(190),
    role_id INT UNSIGNED,
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE vendors (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vendor_code VARCHAR(100) UNIQUE,
    vendor_name VARCHAR(255) NOT NULL,
    tax_id VARCHAR(50),
    bank_name VARCHAR(150),
    bank_account VARCHAR(50),
    bank_branch VARCHAR(150),
    contact_name VARCHAR(150),
    phone VARCHAR(50),
    email VARCHAR(190),
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sap_import_batches (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(100) UNIQUE NOT NULL,
    filename VARCHAR(255) NOT NULL,
    total_records INT DEFAULT 0,
    imported_records INT DEFAULT 0,
    error_records INT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'completed',
    imported_by INT UNSIGNED,
    imported_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (imported_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sap_ap_invoices (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    import_batch_id INT UNSIGNED,
    vendor_code VARCHAR(100),
    vendor_name VARCHAR(255),
    po_doc_num VARCHAR(100),
    grpo_doc_num VARCHAR(100),
    grpo_date DATE NULL,
    grpo_total DECIMAL(15,2) DEFAULT 0,
    ap_invoice_doc_num VARCHAR(100) UNIQUE,
    ap_invoice_date DATE NULL,
    ap_invoice_total DECIMAL(15,2) DEFAULT 0,
    ap_paid_amount DECIMAL(15,2) DEFAULT 0,
    ap_balance DECIMAL(15,2) DEFAULT 0,
    payment_doc_num VARCHAR(100),
    payment_total DECIMAL(15,2) DEFAULT 0,
    payment_status VARCHAR(50) DEFAULT 'Imported',
    is_deleted TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (import_batch_id) REFERENCES sap_import_batches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE finance_import_batches (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(100) UNIQUE NOT NULL,
    filename VARCHAR(255) NOT NULL,
    period VARCHAR(50),
    total_records INT DEFAULT 0,
    imported_records INT DEFAULT 0,
    error_records INT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'completed',
    imported_by INT UNSIGNED,
    imported_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (imported_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE finance_ap_records (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    import_batch_id INT UNSIGNED,
    vendor_name VARCHAR(255),
    invoice_no VARCHAR(100),
    invoice_date DATE NULL,
    due_date DATE NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    wht_amount DECIMAL(15,2) DEFAULT 0,
    net_payable DECIMAL(15,2) DEFAULT 0,
    cheque_date DATE NULL,
    cheque_no VARCHAR(100),
    payment_status VARCHAR(50) DEFAULT 'Imported',
    remark TEXT,
    sap_invoice_id INT UNSIGNED,
    is_deleted TINYINT(1) DEFAULT 0,
    tax_invoice_no VARCHAR(100),
    cheque_bank VARCHAR(150),
    paid_date DATE NULL,
    source_row INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (import_batch_id) REFERENCES finance_import_batches(id),
    FOREIGN KEY (sap_invoice_id) REFERENCES sap_ap_invoices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_no VARCHAR(100) UNIQUE NOT NULL,
    vendor_id INT UNSIGNED,
    vendor_code VARCHAR(100),
    vendor_name VARCHAR(255),
    total_amount DECIMAL(15,2) DEFAULT 0,
    gross_amount DECIMAL(15,2) DEFAULT 0,
    wht_applicable TINYINT(1) DEFAULT 0,
    wht_rate DECIMAL(5,2) DEFAULT 0,
    wht_base_amount DECIMAL(15,2) DEFAULT 0,
    wht_amount DECIMAL(15,2) DEFAULT 0,
    net_payable DECIMAL(15,2) DEFAULT 0,
    due_date DATE NULL,
    payment_method VARCHAR(50) DEFAULT 'cheque',
    status VARCHAR(50) DEFAULT 'draft',
    priority VARCHAR(20) DEFAULT 'normal',
    priority_reason TEXT,
    note TEXT,
    tax_invoice_required TINYINT(1) DEFAULT 1,
    has_po TINYINT(1) DEFAULT 0,
    has_grn TINYINT(1) DEFAULT 0,
    has_invoice TINYINT(1) DEFAULT 0,
    has_tax_invoice TINYINT(1) DEFAULT 0,
    checker_po_accepted TINYINT(1) DEFAULT 0,
    checker_po_comment TEXT,
    checker_invoice_accepted TINYINT(1) DEFAULT 0,
    checker_invoice_comment TEXT,
    checker_gr_accepted TINYINT(1) DEFAULT 0,
    checker_gr_comment TEXT,
    return_to VARCHAR(100),
    return_reason TEXT,
    payment_date DATE NULL,
    payment_reference VARCHAR(100),
    payment_bank VARCHAR(150),
    payer_name VARCHAR(150),
    created_by INT UNSIGNED,
    checked_by INT UNSIGNED,
    checked_at DATETIME NULL,
    submitted_at DATETIME NULL,
    is_deleted TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vendor_id) REFERENCES vendors(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (checked_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_request_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payment_request_id INT UNSIGNED,
    sap_invoice_id INT UNSIGNED,
    ap_invoice_no VARCHAR(100),
    invoice_date DATE NULL,
    invoice_amount DECIMAL(15,2) DEFAULT 0,
    wht_amount DECIMAL(15,2) DEFAULT 0,
    net_amount DECIMAL(15,2) DEFAULT 0,
    due_date DATE NULL,
    remark TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_request_id) REFERENCES payment_requests(id),
    FOREIGN KEY (sap_invoice_id) REFERENCES sap_ap_invoices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE approval_matrix (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    min_amount DECIMAL(15,2) DEFAULT 0,
    max_amount DECIMAL(15,2) NULL,
    approver_role VARCHAR(50) NOT NULL,
    approver_user_id INT UNSIGNED,
    sequence INT DEFAULT 1,
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (approver_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE approval_tasks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payment_request_id INT UNSIGNED,
    approver_id INT UNSIGNED,
    sequence INT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'pending',
    action VARCHAR(50),
    comment TEXT,
    actioned_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_request_id) REFERENCES payment_requests(id),
    FOREIGN KEY (approver_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE approval_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payment_request_id INT UNSIGNED,
    user_id INT UNSIGNED,
    action VARCHAR(50) NOT NULL,
    comment TEXT,
    old_status VARCHAR(50),
    new_status VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_request_id) REFERENCES payment_requests(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_batches (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(100) UNIQUE NOT NULL,
    batch_date DATE NULL,
    payment_type VARCHAR(50) DEFAULT 'cheque',
    total_amount DECIMAL(15,2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'draft',
    is_locked TINYINT(1) DEFAULT 0,
    note TEXT,
    created_by INT UNSIGNED,
    locked_by INT UNSIGNED,
    locked_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (locked_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_batch_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payment_batch_id INT UNSIGNED,
    payment_request_id INT UNSIGNED,
    amount DECIMAL(15,2) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_batch_id) REFERENCES payment_batches(id),
    FOREIGN KEY (payment_request_id) REFERENCES payment_requests(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cheques (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cheque_no VARCHAR(100),
    cheque_date DATE NULL,
    bank VARCHAR(150),
    amount DECIMAL(15,2) DEFAULT 0,
    payee_name VARCHAR(255),
    payment_batch_id INT UNSIGNED,
    payment_request_id INT UNSIGNED,
    vendor_id INT UNSIGNED,
    status VARCHAR(50) DEFAULT 'prepared',
    receiver_name VARCHAR(150),
    received_date DATE NULL,
    void_reason TEXT,
    source_type VARCHAR(50),
    source_id INT UNSIGNED,
    created_by INT UNSIGNED,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_batch_id) REFERENCES payment_batches(id),
    FOREIGN KEY (payment_request_id) REFERENCES payment_requests(id),
    FOREIGN KEY (vendor_id) REFERENCES vendors(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE attachments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    related_type VARCHAR(50) NOT NULL,
    related_id INT UNSIGNED NOT NULL,
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(100),
    file_size INT,
    document_type VARCHAR(100),
    uploaded_by INT UNSIGNED,
    is_deleted TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audit_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED,
    username VARCHAR(50),
    action VARCHAR(50) NOT NULL,
    module VARCHAR(50) NOT NULL,
    record_id INT UNSIGNED,
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(45),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE system_settings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT,
    description TEXT,
    updated_by INT UNSIGNED,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE import_error_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    import_batch_id INT UNSIGNED,
    import_type VARCHAR(50),
    row_number INT,
    field_name VARCHAR(100),
    error_message TEXT,
    raw_data TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    related_type VARCHAR(50),
    related_id INT UNSIGNED,
    recipient_id INT UNSIGNED,
    recipient_email VARCHAR(190),
    subject VARCHAR(255),
    body TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    sent_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification_reads (
    user_id INT UNSIGNED NOT NULL,
    notification_key VARCHAR(100) NOT NULL,
    read_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, notification_key),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_cheques_source ON cheques(source_type, source_id);
CREATE INDEX idx_payment_requests_notification ON payment_requests(status, is_deleted);
CREATE INDEX idx_approval_tasks_notification ON approval_tasks(payment_request_id, approver_id, status, sequence);

-- Seed data -------------------------------------------------------------

INSERT INTO roles (id, name, display_name, description) VALUES
    (1, 'admin', 'Administrator', 'Full system access'),
    (2, 'maker', 'Maker', 'Create payment requests'),
    (3, 'checker', 'Checker', 'Verify payment requests'),
    (4, 'approver', 'Approver', 'Approve payment requests'),
    (5, 'finance_manager', 'Finance Manager', 'Manage payment batches and cash forecast'),
    (6, 'executive', 'MD / Executive', 'View dashboards and approve high-value items');

-- Password hashes below are the same real bcrypt hashes used in
-- schema.sqlite.sql (generated with PHP's password_hash(), verified with
-- password_verify() before being pasted here) for the plaintext demo
-- passwords shown on the login page.
INSERT INTO users (username, password, full_name, email, role_id) VALUES
    ('admin', '$2y$10$TllIkJ2jbsJ41YfnunDVY.pdNNBZHILGoiPmiCiwqUc9pWpyt2Ts6', 'System Admin', 'admin@alumet.co.th', 1),
    ('maker1', '$2y$10$5H3.gQs/mLAk18DWCiDqtuwzxsjvfqBHiA.HQaV7gC3AhlgLtHHTq', 'Finance Maker', 'maker@alumet.co.th', 2),
    ('checker1', '$2y$10$5HPzPQDEm8..WwOHpMmWouKVeRLpzbfbUWtMO8t5GUmUTmc1qXO8u', 'Finance Checker', 'checker@alumet.co.th', 3),
    ('approver1', '$2y$10$ns9/bMFo7b7k5Lr9ul5OTeUnnMYQ2XFilN25lVqT4UAlsPBdRPUDO', 'Finance Approver', 'approver@alumet.co.th', 4),
    ('finance1', '$2y$10$hVmO3JLODFoj7u8qTNSl/uUP7KIl6jf6Xy18632EMxuCsoAyYByUS', 'Finance Manager', 'fm@alumet.co.th', 5),
    ('md1', '$2y$10$JDuOfUBy.9JFwasd2yShHeSASqhP06D.QiNBuC4cCgra2rK16jNRC', 'Managing Director', 'md@alumet.co.th', 6);

INSERT INTO approval_matrix (min_amount, max_amount, approver_role, sequence) VALUES
    (0, 100000, 'finance_manager', 1),
    (100000.01, 500000, 'finance_manager', 1),
    (100000.01, 500000, 'approver', 2),
    (500000.01, 2000000, 'approver', 1),
    (500000.01, 2000000, 'executive', 2),
    (2000000.01, NULL, 'executive', 1);

INSERT INTO system_settings (setting_key, setting_value, description) VALUES
    ('company_name', 'Alumet Co., Ltd.', 'Company name'),
    ('currency', 'THB', 'Default currency'),
    ('date_format', 'd/m/Y', 'Display date format');
