-- Baseline schema for a fresh SQLite database. This is what config/database.php
-- applies to an EMPTY database. It represents the app's actual structure as of
-- the introduction of the migrations system (base tables + every column the old
-- ad hoc ensureColumn() mechanism used to add + corrected seed data), so a fresh
-- database and the already-running production database converge to the same
-- structure with zero migrations needed to catch up.
--
-- Do not edit this file to change structure once it has shipped — add a new
-- numbered file under database/migrations/sqlite/ instead. This file only
-- describes what an empty database gets right now.

CREATE TABLE schema_migrations (
    migration TEXT PRIMARY KEY,
    applied_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    description TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT,
    role_id INTEGER REFERENCES roles(id),
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vendors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vendor_code TEXT UNIQUE,
    vendor_name TEXT NOT NULL,
    tax_id TEXT,
    bank_name TEXT,
    bank_account TEXT,
    bank_branch TEXT,
    contact_name TEXT,
    phone TEXT,
    email TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sap_import_batches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_no TEXT UNIQUE NOT NULL,
    filename TEXT NOT NULL,
    total_records INTEGER DEFAULT 0,
    imported_records INTEGER DEFAULT 0,
    error_records INTEGER DEFAULT 0,
    status TEXT DEFAULT 'completed',
    imported_by INTEGER REFERENCES users(id),
    imported_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sap_ap_invoices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    import_batch_id INTEGER REFERENCES sap_import_batches(id),
    vendor_code TEXT,
    vendor_name TEXT,
    po_doc_num TEXT,
    grpo_doc_num TEXT,
    grpo_date TEXT,
    grpo_total REAL DEFAULT 0,
    ap_invoice_doc_num TEXT UNIQUE,
    ap_invoice_date TEXT,
    ap_invoice_total REAL DEFAULT 0,
    ap_paid_amount REAL DEFAULT 0,
    ap_balance REAL DEFAULT 0,
    payment_doc_num TEXT,
    payment_total REAL DEFAULT 0,
    payment_status TEXT DEFAULT 'Imported',
    is_deleted INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE finance_import_batches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_no TEXT UNIQUE NOT NULL,
    filename TEXT NOT NULL,
    period TEXT,
    total_records INTEGER DEFAULT 0,
    imported_records INTEGER DEFAULT 0,
    error_records INTEGER DEFAULT 0,
    status TEXT DEFAULT 'completed',
    imported_by INTEGER REFERENCES users(id),
    imported_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE finance_ap_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    import_batch_id INTEGER REFERENCES finance_import_batches(id),
    vendor_name TEXT,
    invoice_no TEXT,
    invoice_date TEXT,
    due_date TEXT,
    amount REAL DEFAULT 0,
    wht_amount REAL DEFAULT 0,
    net_payable REAL DEFAULT 0,
    cheque_date TEXT,
    cheque_no TEXT,
    payment_status TEXT DEFAULT 'Imported',
    remark TEXT,
    sap_invoice_id INTEGER REFERENCES sap_ap_invoices(id),
    is_deleted INTEGER DEFAULT 0,
    tax_invoice_no TEXT,
    cheque_bank TEXT,
    paid_date TEXT,
    source_row INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    request_no TEXT UNIQUE NOT NULL,
    vendor_id INTEGER REFERENCES vendors(id),
    vendor_code TEXT,
    vendor_name TEXT,
    total_amount REAL DEFAULT 0,
    gross_amount REAL DEFAULT 0,
    wht_applicable INTEGER DEFAULT 0,
    wht_rate REAL DEFAULT 0,
    wht_base_amount REAL DEFAULT 0,
    wht_amount REAL DEFAULT 0,
    net_payable REAL DEFAULT 0,
    due_date TEXT,
    payment_method TEXT DEFAULT 'cheque',
    status TEXT DEFAULT 'draft',
    priority TEXT DEFAULT 'normal',
    priority_reason TEXT,
    note TEXT,
    tax_invoice_required INTEGER DEFAULT 1,
    has_po INTEGER DEFAULT 0,
    has_grn INTEGER DEFAULT 0,
    has_invoice INTEGER DEFAULT 0,
    has_tax_invoice INTEGER DEFAULT 0,
    checker_po_accepted INTEGER DEFAULT 0,
    checker_po_comment TEXT,
    checker_invoice_accepted INTEGER DEFAULT 0,
    checker_invoice_comment TEXT,
    checker_gr_accepted INTEGER DEFAULT 0,
    checker_gr_comment TEXT,
    return_to TEXT,
    return_reason TEXT,
    payment_date TEXT,
    payment_reference TEXT,
    payment_bank TEXT,
    payer_name TEXT,
    created_by INTEGER REFERENCES users(id),
    checked_by INTEGER REFERENCES users(id),
    checked_at TEXT,
    submitted_at TEXT,
    is_deleted INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_request_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_request_id INTEGER REFERENCES payment_requests(id),
    sap_invoice_id INTEGER REFERENCES sap_ap_invoices(id),
    ap_invoice_no TEXT,
    invoice_date TEXT,
    invoice_amount REAL DEFAULT 0,
    wht_amount REAL DEFAULT 0,
    net_amount REAL DEFAULT 0,
    due_date TEXT,
    remark TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_matrix (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    min_amount REAL DEFAULT 0,
    max_amount REAL,
    approver_role TEXT NOT NULL,
    approver_user_id INTEGER REFERENCES users(id),
    sequence INTEGER DEFAULT 1,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_request_id INTEGER REFERENCES payment_requests(id),
    approver_id INTEGER REFERENCES users(id),
    sequence INTEGER DEFAULT 1,
    status TEXT DEFAULT 'pending',
    action TEXT,
    comment TEXT,
    actioned_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_request_id INTEGER REFERENCES payment_requests(id),
    user_id INTEGER REFERENCES users(id),
    action TEXT NOT NULL,
    comment TEXT,
    old_status TEXT,
    new_status TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_batches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_no TEXT UNIQUE NOT NULL,
    batch_date TEXT,
    payment_type TEXT DEFAULT 'cheque',
    total_amount REAL DEFAULT 0,
    status TEXT DEFAULT 'draft',
    is_locked INTEGER DEFAULT 0,
    note TEXT,
    created_by INTEGER REFERENCES users(id),
    locked_by INTEGER REFERENCES users(id),
    locked_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_batch_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_batch_id INTEGER REFERENCES payment_batches(id),
    payment_request_id INTEGER REFERENCES payment_requests(id),
    amount REAL DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cheques (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cheque_no TEXT,
    cheque_date TEXT,
    bank TEXT,
    amount REAL DEFAULT 0,
    payee_name TEXT,
    payment_batch_id INTEGER REFERENCES payment_batches(id),
    payment_request_id INTEGER REFERENCES payment_requests(id),
    vendor_id INTEGER REFERENCES vendors(id),
    status TEXT DEFAULT 'prepared',
    receiver_name TEXT,
    received_date TEXT,
    void_reason TEXT,
    source_type TEXT,
    source_id INTEGER,
    created_by INTEGER REFERENCES users(id),
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attachments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    related_type TEXT NOT NULL,
    related_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    file_type TEXT,
    file_size INTEGER,
    document_type TEXT,
    uploaded_by INTEGER REFERENCES users(id),
    is_deleted INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id),
    username TEXT,
    action TEXT NOT NULL,
    module TEXT NOT NULL,
    record_id INTEGER,
    old_value TEXT,
    new_value TEXT,
    ip_address TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE system_settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    setting_key TEXT UNIQUE NOT NULL,
    setting_value TEXT,
    description TEXT,
    updated_by INTEGER REFERENCES users(id),
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE import_error_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    import_batch_id INTEGER,
    import_type TEXT,
    row_number INTEGER,
    field_name TEXT,
    error_message TEXT,
    raw_data TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    related_type TEXT,
    related_id INTEGER,
    recipient_id INTEGER,
    recipient_email TEXT,
    subject TEXT,
    body TEXT,
    status TEXT DEFAULT 'pending',
    sent_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_reads (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    notification_key TEXT NOT NULL,
    read_at TEXT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, notification_key)
);

CREATE INDEX idx_cheques_source ON cheques(source_type, source_id);
CREATE INDEX idx_payment_requests_notification ON payment_requests(status, is_deleted);
CREATE INDEX idx_approval_tasks_notification ON approval_tasks(payment_request_id, approver_id, status, sequence);

-- Seed data -------------------------------------------------------------

INSERT INTO roles (id, name, display_name, description) VALUES
    (1, 'admin', 'Administrator', 'Full system access'),
    (2, 'maker', 'Maker', 'Create payment requests'),
    (3, 'checker', 'Checker', 'Verify payment requests'),
    (4, 'approver', 'Approver', 'Approve payment requests'),
    (5, 'finance_manager', 'Finance Manager', 'Manage payment batches and cash forecast'),
    (6, 'executive', 'MD / Executive', 'View dashboards and approve high-value items');

-- Password hashes below are real bcrypt hashes (generated with PHP's
-- password_hash(), verified with password_verify() before being pasted
-- here) of the plaintext demo passwords shown on the login page
-- (admin1234, maker1234, checker1234, approver1234, finance1234, md1234) —
-- same seed accounts as the previous ad hoc seeder.
INSERT INTO users (username, password, full_name, email, role_id) VALUES
    ('admin', '$2y$10$TllIkJ2jbsJ41YfnunDVY.pdNNBZHILGoiPmiCiwqUc9pWpyt2Ts6', 'System Admin', 'admin@alumet.co.th', 1),
    ('maker1', '$2y$10$5H3.gQs/mLAk18DWCiDqtuwzxsjvfqBHiA.HQaV7gC3AhlgLtHHTq', 'Finance Maker', 'maker@alumet.co.th', 2),
    ('checker1', '$2y$10$5HPzPQDEm8..WwOHpMmWouKVeRLpzbfbUWtMO8t5GUmUTmc1qXO8u', 'Finance Checker', 'checker@alumet.co.th', 3),
    ('approver1', '$2y$10$ns9/bMFo7b7k5Lr9ul5OTeUnnMYQ2XFilN25lVqT4UAlsPBdRPUDO', 'Finance Approver', 'approver@alumet.co.th', 4),
    ('finance1', '$2y$10$hVmO3JLODFoj7u8qTNSl/uUP7KIl6jf6Xy18632EMxuCsoAyYByUS', 'Finance Manager', 'fm@alumet.co.th', 5),
    ('md1', '$2y$10$JDuOfUBy.9JFwasd2yShHeSASqhP06D.QiNBuC4cCgra2rK16jNRC', 'Managing Director', 'md@alumet.co.th', 6);

-- Approval matrix boundaries corrected from the original whole-baht seed
-- (100001/500001/2000001), which left cent-valued payments between tiers
-- with no approver assigned.
INSERT INTO approval_matrix (min_amount, max_amount, approver_role, sequence) VALUES
    (0, 100000, 'finance_manager', 1),
    (100000.01, 500000, 'finance_manager', 1),
    (100000.01, 500000, 'approver', 2),
    (500000.01, 2000000, 'approver', 1),
    (500000.01, 2000000, 'executive', 2),
    (2000000.01, NULL, 'executive', 1);

INSERT INTO system_settings (setting_key, setting_value, description) VALUES
    ('company_name', 'Alumet Co., Ltd.', 'Company name'),
    ('currency', 'THB', 'Default currency'),
    ('date_format', 'd/m/Y', 'Display date format');
